"""The language-agnostic half of the code generator.

Language emitters (``api_generator.python.emitter``, future
``js``/``ts``/...) subclass :class:`Emitter` and provide only the two
language-specific pieces: rendering the file set from the shared IR
and validating the rendered sources (formatter, linter, compiler).
The transactional publication - staging directory next to the target,
atomic replace, no partial output on failure - lives here once.
"""

from __future__ import annotations

import os
import shutil
import tempfile
from abc import ABC, abstractmethod
from pathlib import Path
from typing import ClassVar

from .ir import SpecIR, build_ir
from .loader import load_spec

GENERATED_NOTE = "Generated by codegen from the OpenAPI spec - do not edit."


class Emitter(ABC):
    """Transactional spec-to-package generator for one target language."""

    #: files the generator owns inside the otherwise static package
    files: ClassVar[tuple[str, ...]]

    @abstractmethod
    def render(self, ir: SpecIR) -> dict[str, str]:
        """Render every owned file: name -> source text."""

    @abstractmethod
    def validate(self, paths: list[Path]) -> None:
        """Gate the staged sources (format, lint, compile); raise on failure."""

    def generate(self, spec_source: str | Path, package_dir: Path) -> Path:
        """Write the spec-dependent modules into the target package.

        The transport adapters and other spec-independent modules live
        in the package as regular source files; only the API surface
        is generated.

        Publication is transactional: everything is rendered and
        validated inside a staging directory first, and only a fully
        validated set replaces the owned files - a failure at any step
        leaves the previously working package untouched.
        """
        spec = load_spec(spec_source)
        ir = build_ir(spec)
        package_dir.mkdir(parents=True, exist_ok=True)

        renders = self.render(ir)
        assert set(renders) == set(self.files)
        # the staging dir lives next to the destination: same
        # filesystem, so the final os.replace is atomic
        staging = Path(tempfile.mkdtemp(prefix=".generate-", dir=package_dir.parent))
        try:
            for name, content in renders.items():
                (staging / name).write_text(content, encoding="utf-8")
            self.validate([staging / name for name in renders])
            for name in renders:
                os.replace(staging / name, package_dir / name)
        finally:
            shutil.rmtree(staging, ignore_errors=True)
        return package_dir
