"""Shared Go names, type rendering, and package validation."""

from __future__ import annotations

import json
import re

from ..ir import ModelDef, TypeKind, TypeRef

HEADER = "// Code generated by codegen from the OpenAPI spec. DO NOT EDIT.\n"

_INITIALISMS = {
    "api": "API",
    "cpu": "CPU",
    "gid": "GID",
    "http": "HTTP",
    "https": "HTTPS",
    "id": "ID",
    "ip": "IP",
    "json": "JSON",
    "sha256": "SHA256",
    "sse": "SSE",
    "uid": "UID",
    "uri": "URI",
    "url": "URL",
    "uuid": "UUID",
    "vm": "VM",
}
_SPECIAL_NAMES = {"whoami": "WhoAmI"}
_WORD_RE = re.compile(r"[A-Z]+(?=[A-Z][a-z]|[0-9]|$)|[A-Z]?[a-z]+|[0-9]+")
_PACKAGE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
GO_KEYWORDS = {
    "break",
    "case",
    "chan",
    "const",
    "continue",
    "default",
    "defer",
    "else",
    "fallthrough",
    "for",
    "func",
    "go",
    "goto",
    "if",
    "import",
    "interface",
    "map",
    "package",
    "range",
    "return",
    "select",
    "struct",
    "switch",
    "type",
    "var",
}


def _identifier_words(name: str) -> list[str]:
    words: list[str] = []
    for part in re.split(r"[^A-Za-z0-9]+", name):
        if not part:
            continue
        if part.lower() in _INITIALISMS:
            words.append(part)
            continue
        tokens = _WORD_RE.findall(part)
        index = 0
        while index < len(tokens):
            if index + 1 < len(tokens):
                combined = (tokens[index] + tokens[index + 1]).lower()
                if combined in _INITIALISMS:
                    words.append(combined)
                    index += 2
                    continue
            words.append(tokens[index])
            index += 1
    return words


def go_name(name: str) -> str:
    """Convert an IR name to an exported, idiomatic Go identifier."""
    special = _SPECIAL_NAMES.get(name.lower())
    if special is not None:
        return special
    rendered: list[str] = []
    for word in _identifier_words(name):
        initialism = _INITIALISMS.get(word.lower())
        rendered.append(initialism if initialism is not None else word.capitalize())
    result = "".join(rendered) or "X"
    if result[0].isdigit():
        result = "X" + result
    return result


def _require_name(type_ref: TypeRef) -> str:
    if type_ref.name is None:
        raise ValueError(f"{type_ref.kind.name} type has no name")
    return go_name(type_ref.name)


def _require_argument(type_ref: TypeRef) -> TypeRef:
    if len(type_ref.arguments) != 1:
        raise ValueError(
            f"{type_ref.kind.name} type needs one argument, got "
            f"{len(type_ref.arguments)}"
        )
    return type_ref.arguments[0]


def is_string_integer_union(type_ref: TypeRef) -> bool:
    return (
        type_ref.kind is TypeKind.UNION
        and {item.kind for item in type_ref.arguments}
        == {TypeKind.STRING, TypeKind.INTEGER}
        and len(type_ref.arguments) == 2
    )


def _go_type(type_ref: TypeRef) -> str:
    atoms = {
        TypeKind.ANY: "any",
        TypeKind.STRING: "string",
        TypeKind.INTEGER: "int64",
        TypeKind.NUMBER: "float64",
        TypeKind.BOOLEAN: "bool",
        TypeKind.DATETIME: "time.Time",
        TypeKind.BYTES: "[]byte",
        TypeKind.BINARY_STREAM: "io.Reader",
    }
    atom = atoms.get(type_ref.kind)
    if atom is not None:
        return atom
    if type_ref.kind in (TypeKind.MODEL, TypeKind.ENUM, TypeKind.ALIAS):
        return _require_name(type_ref)
    if type_ref.kind is TypeKind.LITERAL:
        return "string"
    if type_ref.kind in (TypeKind.LIST, TypeKind.SEQUENCE):
        return "[]" + go_type(_require_argument(type_ref))
    if type_ref.kind is TypeKind.MAP:
        return "map[string]" + go_type(_require_argument(type_ref))
    if type_ref.kind is TypeKind.UNION:
        if is_string_integer_union(type_ref):
            return "StringOrInt64"
        return "json.RawMessage"
    raise ValueError(f"unsupported Go type kind: {type_ref.kind.name}")


def go_type(type_ref: TypeRef, *, nullable: bool = False) -> str:
    """Render one semantic type as a compileable Go type."""
    rendered = _go_type(type_ref)
    return "*" + rendered if nullable else rendered


def _go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def validate_package_name(package_name: str) -> str:
    if not _PACKAGE_RE.fullmatch(package_name) or package_name in GO_KEYWORDS:
        raise ValueError(f"invalid Go package name: {package_name!r}")
    return package_name


def model_field_names(model: ModelDef) -> list[str]:
    reserved = {
        "AsBytes",
        "AsText",
        "MarshalJSON",
        "NormalizeMode",
        "SetMode",
        "UnmarshalJSON",
    }
    used: set[str] = set()
    result: list[str] = []
    for field in model.fields:
        base = go_name(field.name)
        if base in reserved:
            base += "Field"
        candidate = base
        suffix = 2
        while candidate in used:
            candidate = f"{base}{suffix}"
            suffix += 1
        used.add(candidate)
        result.append(candidate)
    return result


def go_model_field_names(model: ModelDef) -> dict[str, str]:
    """Map each exact JSON wire name to its generated Go struct field."""
    names = model_field_names(model)
    return {field.wire_name: names[index] for index, field in enumerate(model.fields)}
