"""Render generated Go request builders and client methods."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass

from ..ir import (
    ArgumentDef,
    ArgumentPresence,
    BodyDef,
    BodyKind,
    ModelDef,
    OperationDef,
    ParameterDef,
    ParameterEncoding,
    ParameterLocation,
    ResponseMode,
    SpecIR,
    SuccessPolicy,
    TypeKind,
)
from .naming import (
    GO_KEYWORDS,
    go_model_field_names,
    go_name,
    go_type,
    validate_package_name,
)

DEFAULT_PACKAGE_NAME = "contree"
HEADER = "// Code generated by codegen from the OpenAPI spec. DO NOT EDIT."

_RESERVED_LOCALS = GO_KEYWORDS | {
    "body",
    "ctx",
    "err",
    "formatted",
    "headers",
    "options",
    "payload",
    "query",
    "requestPath",
    "response",
    "spec",
    "value",
}


def _go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def go_operation_name(name: str) -> str:
    """Reserve SpawnInstance for the plain-options, operation-ID helper."""
    if name == "spawn_instance":
        return "SpawnInstanceWithResponse"
    return go_name(name)


def _lower_exported_name(exported: str) -> str:
    if len(exported) == 1:
        return exported.lower()
    if not any(character.islower() for character in exported):
        return exported.lower()
    if exported[1].islower():
        return exported[0].lower() + exported[1:]
    end = 1
    while end < len(exported) and exported[end].isupper():
        end += 1
    if end < len(exported):
        end -= 1
    return exported[:end].lower() + exported[end:]


def _local_name(name: str) -> str:
    """Convert an IR name to an unexported Go identifier."""
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", name) if part]
    if len(parts) > 1:
        first, *rest = parts
        return _lower_exported_name(go_name(first)) + "".join(map(go_name, rest))
    return _lower_exported_name(go_name(name))


def _indent(lines: list[str], levels: int = 1) -> list[str]:
    prefix = "\t" * levels
    return [prefix + line if line else "" for line in lines]


def _function_signature(
    prefix: str,
    parameters: list[str],
    result: str,
) -> list[str]:
    lines = [prefix + "("]
    lines.extend(f"\t{parameter}," for parameter in parameters)
    lines.append(f") {result} {{")
    return lines


def _optional_type(argument: ArgumentDef, rendered_type: str) -> str:
    if argument.presence is ArgumentPresence.OMIT_IF_FALSE:
        if argument.type.kind is not TypeKind.BOOLEAN:
            raise ValueError(
                f"OMIT_IF_FALSE argument {argument.name!r} must be boolean"
            )
        return "bool"
    if argument.presence is ArgumentPresence.OMIT_IF_NULL:
        return f"*{rendered_type}"
    if argument.presence is ArgumentPresence.OMIT_IF_UNSET:
        return f"Optional[{rendered_type}]"
    raise ValueError(f"required argument {argument.name!r} cannot be an option")


def _status_union_type(argument: ArgumentDef) -> str | None:
    if argument.type.kind is not TypeKind.UNION:
        return None
    variants = argument.type.arguments
    if len(variants) != 2 or not any(
        variant.kind is TypeKind.STRING for variant in variants
    ):
        return None
    named = next(
        (
            variant
            for variant in variants
            if variant.kind is TypeKind.ENUM and variant.name is not None
        ),
        None,
    )
    return go_type(named) if named is not None else None


@dataclass(frozen=True)
class _ArgumentNames:
    local: str
    field: str


class _OperationRenderer:
    def __init__(self, operation: OperationDef, models: dict[str, ModelDef]) -> None:
        self.operation = operation
        self.models = models
        self.arguments: dict[str, ArgumentDef] = {}
        self.names: dict[str, _ArgumentNames] = {}
        used_locals = set(_RESERVED_LOCALS)
        used_fields: set[str] = set()
        for argument in operation.arguments:
            if argument.name in self.arguments:
                raise ValueError(
                    f"operation {operation.name!r} has duplicate argument "
                    f"{argument.name!r}"
                )
            local_base = _local_name(argument.name)
            local = local_base
            suffix = 2
            while local in used_locals:
                local = (
                    f"{local_base}Arg" if suffix == 2 else f"{local_base}Arg{suffix}"
                )
                suffix += 1
            used_locals.add(local)

            field = go_name(argument.name)
            if field in used_fields:
                raise ValueError(
                    f"operation {operation.name!r} has colliding Go option field "
                    f"{field!r}"
                )
            used_fields.add(field)
            self.arguments[argument.name] = argument
            self.names[argument.name] = _ArgumentNames(local, field)

    @property
    def method_name(self) -> str:
        return go_operation_name(self.operation.name)

    @property
    def options_name(self) -> str:
        return self.method_name + "Options"

    @property
    def required_arguments(self) -> list[ArgumentDef]:
        return [argument for argument in self.operation.arguments if argument.required]

    @property
    def optional_arguments(self) -> list[ArgumentDef]:
        return [
            argument for argument in self.operation.arguments if not argument.required
        ]

    def argument(self, name: str) -> ArgumentDef:
        try:
            return self.arguments[name]
        except KeyError as exc:
            raise ValueError(
                f"operation {self.operation.name!r} references unknown argument "
                f"{name!r}"
            ) from exc

    def argument_type(self, argument: ArgumentDef) -> str:
        body = self.operation.request.body
        if (
            body is not None
            and body.kind is BodyKind.BINARY
            and any(binding.argument == argument.name for binding in body.bindings)
        ):
            return "io.Reader"
        parameters = [
            parameter
            for parameter in self.operation.request.parameters
            if parameter.argument == argument.name
        ]
        if any(parameter.repeatable for parameter in parameters):
            return "[]string"
        if any(
            parameter.encoding is ParameterEncoding.TIME for parameter in parameters
        ):
            # Go has no value union for string, numbers, and time.Time.
            # formatTimeParam validates this value before transport.
            return "any"
        status_type = _status_union_type(argument)
        if status_type is not None and parameters:
            return status_type
        return go_type(argument.type, nullable=argument.required and argument.nullable)

    def argument_reference(self, argument: ArgumentDef) -> str:
        names = self.names[argument.name]
        if argument.required:
            return names.local
        return f"options.{names.field}"

    def parameters(self, *, context: bool) -> list[str]:
        parameters = ["ctx context.Context"] if context else []
        parameters.extend(
            f"{self.names[argument.name].local} {self.argument_type(argument)}"
            for argument in self.required_arguments
        )
        if self.optional_arguments:
            parameters.append(f"options *{self.options_name}")
        return parameters

    def builder_arguments(self) -> str:
        arguments = [
            self.names[argument.name].local for argument in self.required_arguments
        ]
        if self.optional_arguments:
            arguments.append("options")
        return ", ".join(arguments)

    def render_options(self) -> str | None:
        optional = self.optional_arguments
        if not optional:
            return None
        lines = [
            f"// {self.options_name} contains optional arguments for "
            f"{self.method_name}.",
            f"type {self.options_name} struct {{",
        ]
        for argument in optional:
            rendered = self.argument_type(argument)
            field_type = _optional_type(argument, rendered)
            lines.append(f"\t{self.names[argument.name].field} {field_type}")
        lines.append("}")
        return "\n".join(lines)

    def _path_expression(self) -> str:
        by_wire: dict[str, ParameterDef] = {}
        for parameter in self.operation.request.parameters:
            if parameter.location is not ParameterLocation.PATH:
                continue
            argument = self.argument(parameter.argument)
            if not argument.required:
                raise ValueError(
                    f"path argument {parameter.argument!r} in "
                    f"{self.operation.name!r} must be required"
                )
            by_wire[parameter.wire_name] = parameter

        parts: list[str] = []
        position = 0
        for match in re.finditer(r"\{([^{}]+)\}", self.operation.path):
            parts.append(_go_string(self.operation.path[position : match.start()]))
            wire_name = match.group(1)
            try:
                parameter = by_wire[wire_name]
            except KeyError as exc:
                raise ValueError(
                    f"path {self.operation.path!r} has no parameter for {wire_name!r}"
                ) from exc
            argument = self.argument(parameter.argument)
            parts.append(f"quotePath({self.argument_reference(argument)})")
            position = match.end()
        parts.append(_go_string(self.operation.path[position:]))
        return " + ".join(part for part in parts if part != '""') or '""'

    def _render_query_value(
        self,
        parameter: ParameterDef,
        value: str,
    ) -> list[str]:
        wire_name = _go_string(parameter.wire_name)
        repeatable = str(parameter.repeatable).lower()
        if parameter.encoding is ParameterEncoding.TIME:
            return [
                f"formatted, err := formatTimeParam({value})",
                "if err != nil {",
                "\treturn requestSpec{}, err",
                "}",
                (
                    f"if err := addQueryValue(query, {wire_name}, formatted, "
                    f"{repeatable}); err != nil {{"
                ),
                "\treturn requestSpec{}, err",
                "}",
            ]
        if parameter.encoding is ParameterEncoding.ONE_IF_TRUE:
            value = '"1"'
        return [
            (
                f"if err := addQueryValue(query, {wire_name}, {value}, "
                f"{repeatable}); err != nil {{"
            ),
            "\treturn requestSpec{}, err",
            "}",
        ]

    def _render_header_value(
        self,
        parameter: ParameterDef,
        argument: ArgumentDef,
        value: str,
    ) -> list[str]:
        wire_name = _go_string(parameter.wire_name)
        if parameter.encoding is ParameterEncoding.TIME:
            return [
                f"formatted, err := formatTimeParam({value})",
                "if err != nil {",
                "\treturn requestSpec{}, err",
                "}",
                f"headers.Set({wire_name}, formatted)",
            ]
        if parameter.encoding is ParameterEncoding.ONE_IF_TRUE:
            return [f'headers.Set({wire_name}, "1")']
        rendered_type = self.argument_type(argument)
        if (
            parameter.encoding is ParameterEncoding.IDENTITY
            and rendered_type == "string"
        ):
            rendered = value
        else:
            rendered = f"fmt.Sprint({value})"
        return [f"headers.Set({wire_name}, {rendered})"]

    def _render_parameter_value(
        self,
        parameter: ParameterDef,
        argument: ArgumentDef,
        value: str,
    ) -> list[str]:
        if parameter.location is ParameterLocation.QUERY:
            return self._render_query_value(parameter, value)
        if parameter.location is ParameterLocation.HEADER:
            return self._render_header_value(parameter, argument, value)
        raise ValueError(f"cannot assign path parameter {parameter.wire_name!r}")

    def _render_parameter(self, parameter: ParameterDef) -> list[str]:
        argument = self.argument(parameter.argument)
        if parameter.location is ParameterLocation.PATH:
            return []
        names = self.names[argument.name]
        if argument.required:
            assignment = self._render_parameter_value(
                parameter,
                argument,
                names.local,
            )
            if parameter.encoding is ParameterEncoding.ONE_IF_TRUE:
                return [f"if {names.local} {{", *_indent(assignment), "}"]
            if parameter.encoding is ParameterEncoding.TIME:
                return ["{", *_indent(assignment), "}"]
            return assignment

        if argument.presence is ArgumentPresence.OMIT_IF_FALSE:
            assignment = self._render_parameter_value(
                parameter,
                argument,
                f"options.{names.field}",
            )
            return [
                f"if options != nil && options.{names.field} {{",
                *_indent(assignment),
                "}",
            ]

        if argument.presence is ArgumentPresence.OMIT_IF_NULL:
            assignment = self._render_parameter_value(
                parameter,
                argument,
                f"*options.{names.field}",
            )
            condition = f"options != nil && options.{names.field} != nil"
            if parameter.encoding is ParameterEncoding.ONE_IF_TRUE:
                condition += f" && *options.{names.field}"
            return [
                f"if {condition} {{",
                *_indent(assignment),
                "}",
            ]

        assignment = self._render_parameter_value(parameter, argument, "value")
        if parameter.encoding is ParameterEncoding.ONE_IF_TRUE:
            assignment = ["if value {", *_indent(assignment), "}"]
        return [
            "if options != nil {",
            f"\tif value, ok := options.{names.field}.Value(); ok {{",
            *_indent(assignment, 2),
            "\t}",
            "}",
        ]

    def _body_model(self, body: BodyDef) -> tuple[ModelDef, str]:
        model_ref = body.model
        if (
            model_ref is None
            or model_ref.kind is not TypeKind.MODEL
            or model_ref.name is None
        ):
            raise ValueError(
                f"operation {self.operation.name!r} JSON_MODEL body has no model"
            )
        try:
            return self.models[model_ref.name], go_type(model_ref)
        except KeyError as exc:
            raise ValueError(
                f"operation {self.operation.name!r} uses unknown body model "
                f"{model_ref.name!r}"
            ) from exc

    def _render_model_body(self, body: BodyDef) -> list[str]:
        model, model_name = self._body_model(body)
        field_names = go_model_field_names(model)
        fields_by_wire = {field.wire_name: field for field in model.fields}
        required_fields: list[str] = []
        optional_fields: list[tuple[str, ArgumentDef]] = []
        for binding in body.bindings:
            argument = self.argument(binding.argument)
            try:
                field_name = field_names[binding.wire_name]
                field = fields_by_wire[binding.wire_name]
            except KeyError as exc:
                raise ValueError(
                    f"operation {self.operation.name!r} body model "
                    f"{model.name!r} has no wire field {binding.wire_name!r}"
                ) from exc
            if argument.required:
                value = self.argument_reference(argument)
                if not field.required:
                    value = f"Some({value})"
                required_fields.append(f"{field_name}: {value},")
            else:
                if field.required:
                    raise ValueError(
                        f"optional argument {argument.name!r} cannot initialize "
                        f"required model field {binding.wire_name!r}"
                    )
                optional_fields.append((field_name, argument))

        lines = [f"payload := {model_name}{{"]
        lines.extend(_indent(required_fields))
        lines.append("}")
        if optional_fields:
            lines.append("if options != nil {")
            for field_name, argument in optional_fields:
                option = f"options.{self.names[argument.name].field}"
                if argument.presence is ArgumentPresence.OMIT_IF_FALSE:
                    lines.extend(
                        (
                            f"\tif {option} {{",
                            f"\t\tpayload.{field_name} = Some(true)",
                            "\t}",
                        )
                    )
                elif argument.presence is ArgumentPresence.OMIT_IF_UNSET:
                    lines.append(f"\tpayload.{field_name} = {option}")
                else:
                    lines.extend(
                        (
                            f"\tif {option} != nil {{",
                            f"\t\tpayload.{field_name} = Some(*{option})",
                            "\t}",
                        )
                    )
            lines.append("}")
        return lines

    def _render_inline_body(self, body: BodyDef) -> list[str]:
        required_fields: list[str] = []
        optional_fields: list[tuple[str, ArgumentDef]] = []
        for binding in body.bindings:
            argument = self.argument(binding.argument)
            if argument.required:
                required_fields.append(
                    f"{_go_string(binding.wire_name)}: "
                    f"{self.argument_reference(argument)},"
                )
            else:
                optional_fields.append((binding.wire_name, argument))
        lines = ["payload := map[string]any{"]
        lines.extend(_indent(required_fields))
        lines.append("}")
        for wire_name, argument in optional_fields:
            option = f"options.{self.names[argument.name].field}"
            if argument.presence is ArgumentPresence.OMIT_IF_FALSE:
                lines.extend(
                    (
                        f"if options != nil && {option} {{",
                        f"\tpayload[{_go_string(wire_name)}] = true",
                        "}",
                    )
                )
            elif argument.presence is ArgumentPresence.OMIT_IF_UNSET:
                lines.extend(
                    (
                        f"if options != nil && {option}.IsSet() {{",
                        f"\tpayload[{_go_string(wire_name)}] = {option}",
                        "}",
                    )
                )
            else:
                lines.extend(
                    (
                        f"if options != nil && {option} != nil {{",
                        f"\tpayload[{_go_string(wire_name)}] = *{option}",
                        "}",
                    )
                )
        return lines

    def _render_body(self) -> list[str]:
        body = self.operation.request.body
        if body is None:
            return []
        if body.kind is BodyKind.JSON_MODEL:
            payload = self._render_model_body(body)
        elif body.kind is BodyKind.JSON_INLINE:
            payload = self._render_inline_body(body)
        elif body.kind is BodyKind.BINARY:
            if len(body.bindings) != 1:
                raise ValueError(
                    f"operation {self.operation.name!r} binary body needs one binding"
                )
            argument = self.argument(body.bindings[0].argument)
            if not argument.required:
                raise ValueError(
                    f"operation {self.operation.name!r} binary body must be required"
                )
            return [f"body := oneShotBody({self.argument_reference(argument)})"]
        else:
            raise ValueError(f"unsupported request body kind: {body.kind}")
        return [
            *payload,
            "body, err := jsonBody(payload)",
            "if err != nil {",
            "\treturn requestSpec{}, err",
            "}",
        ]

    def render_builder(self) -> str:
        lines = _function_signature(
            f"func build{self.method_name}",
            self.parameters(context=False),
            "(requestSpec, error)",
        )
        query = any(
            parameter.location is ParameterLocation.QUERY
            for parameter in self.operation.request.parameters
        )
        headers = any(
            parameter.location is ParameterLocation.HEADER
            for parameter in self.operation.request.parameters
        )
        body: list[str] = []
        if query:
            body.append("query := make(url.Values)")
        if headers:
            body.append("headers := make(http.Header)")
        for parameter in self.operation.request.parameters:
            body.extend(self._render_parameter(parameter))
        body.extend(self._render_body())
        body.append(f"requestPath := {self._path_expression()}")
        body.extend(
            (
                "return requestSpec{",
                f"\tmethod: {_go_string(self.operation.http_method)},",
            )
        )
        body.append("\tpath: requestPath,")
        if query:
            body.append("\tquery: query,")
        if headers:
            body.append("\theaders: headers,")
        request_body = self.operation.request.body
        if request_body is not None:
            body.append("\tbody: body,")
            content_type = (
                "application/octet-stream"
                if request_body.kind is BodyKind.BINARY
                else "application/json"
            )
            body.append(f"\tcontentType: {_go_string(content_type)},")
        if self.operation.request.accept is not None:
            body.append(f"\taccept: {_go_string(self.operation.request.accept)},")
        idempotent = str(self.operation.request.idempotent).lower()
        body.extend((f"\tidempotent: {idempotent},", "}, nil"))
        lines.extend(_indent(body))
        lines.append("}")
        return "\n".join(lines)

    def response_policy(self) -> str:
        response = self.operation.response
        if response.success is SuccessPolicy.ANY_2XX:
            return "acceptAny2xx"
        statuses = ", ".join(str(status) for status in response.success_statuses)
        return f"acceptStatuses({statuses})"

    def result_type(self, *, stream_bytes: bool = False) -> str | None:
        mode = self.operation.response.mode
        if stream_bytes or mode is ResponseMode.BYTE_STREAM:
            return "io.ReadCloser"
        if mode is ResponseMode.EMPTY:
            return None
        if mode is ResponseMode.STATUS_BOOL:
            return "bool"
        if mode is ResponseMode.LOCATION:
            return "string"
        if mode is ResponseMode.BYTES:
            return "[]byte"
        if mode is ResponseMode.SSE:
            return "iter.Seq2[OperationEvent, error]"
        if mode is ResponseMode.JSON:
            response_type = self.operation.response.type
            if response_type is None:
                raise ValueError(
                    f"operation {self.operation.name!r} has no JSON response type"
                )
            return go_type(response_type)
        raise ValueError(f"unsupported response mode: {mode}")

    def _response_call(self, *, stream_bytes: bool, raw_stream: bool) -> str:
        response = self.operation.response
        policy = self.response_policy()
        if raw_stream:
            return f"rawStreamResponse(response, {policy})"
        if stream_bytes or response.mode is ResponseMode.BYTE_STREAM:
            return f"streamResponse(response, {policy})"
        if response.mode is ResponseMode.JSON:
            result_type = self.result_type()
            assert result_type is not None
            if response.json_path:
                path = ", ".join(_go_string(part) for part in response.json_path)
                return (
                    f"decodeJSONPathResponse[{result_type}](response, {policy}, {path})"
                )
            return f"decodeJSONResponse[{result_type}](response, {policy})"
        if response.mode is ResponseMode.EMPTY:
            return f"emptyResponse(response, {policy})"
        if response.mode is ResponseMode.STATUS_BOOL:
            false_statuses = "".join(
                f", {status}" for status in response.false_statuses
            )
            return f"booleanResponse(response, {policy}{false_statuses})"
        if response.mode is ResponseMode.LOCATION:
            if response.header_name is None:
                raise ValueError(
                    f"operation {self.operation.name!r} has no location header"
                )
            return (
                f"locationResponse(response, {policy}, "
                f"{_go_string(response.header_name)})"
            )
        if response.mode is ResponseMode.BYTES:
            return f"byteResponse(response, {policy})"
        if response.mode is ResponseMode.SSE:
            return f"newEventStream(response, {policy})"
        raise ValueError(f"unsupported response mode: {response.mode}")

    def render_method(
        self,
        *,
        stream_bytes: bool = False,
        raw_stream: bool = False,
        event_opener: bool = False,
    ) -> str:
        if self.operation.response.mode is ResponseMode.SSE and not event_opener:
            return (
                self.render_event_iterator()
                + "\n\n"
                + self.render_method(event_opener=True)
            )
        suffix = "Raw" if raw_stream else "Stream" if stream_bytes else ""
        method_name = self.method_name + suffix
        if event_opener:
            method_name = "open" + method_name
        result_type = (
            "*eventStream"
            if event_opener
            else self.result_type(stream_bytes=stream_bytes)
        )
        result = "error" if result_type is None else f"({result_type}, error)"
        summary = (
            f"streams the encoded response body from {self.method_name}."
            if raw_stream
            else f"streams the response body from {self.method_name}."
            if stream_bytes
            else f"calls {self.operation.http_method} {self.operation.path}."
        )
        lines = [f"// {method_name} {summary}"]
        lines.extend(
            _function_signature(
                f"func (c *Client) {method_name}",
                self.parameters(context=True),
                result,
            )
        )
        body = [
            f"spec, err := build{self.method_name}({self.builder_arguments()})",
            "if err != nil {",
        ]
        if result_type is None:
            body.append("\treturn err")
        else:
            body.extend((f"\tvar zero {result_type}", "\treturn zero, err"))
        streaming = stream_bytes or self.operation.response.mode in (
            ResponseMode.BYTE_STREAM,
            ResponseMode.SSE,
        )
        do_method = "doRawStream" if raw_stream else "doStream" if streaming else "do"
        body.extend(
            ("}", f"response, err := c.{do_method}(ctx, spec)", "if err != nil {")
        )
        if result_type is None:
            body.append("\treturn err")
        else:
            body.extend((f"\tvar zero {result_type}", "\treturn zero, err"))
        body.extend(
            (
                "}",
                "return "
                + self._response_call(
                    stream_bytes=stream_bytes,
                    raw_stream=raw_stream,
                ),
            )
        )
        lines.extend(_indent(body))
        lines.append("}")
        return "\n".join(lines)

    def render_event_iterator(self) -> str:
        lines = [
            f"// {self.method_name} lazily yields operation events.",
            "// Each traversal opens a new stream and closes it when iteration ends.",
            "// The first error is yielded with a zero event, then iteration stops.",
        ]
        lines.extend(
            _function_signature(
                f"func (c *Client) {self.method_name}",
                self.parameters(context=True),
                "iter.Seq2[OperationEvent, error]",
            )
        )
        arguments = ", ".join(
            part for part in ("ctx", self.builder_arguments()) if part
        )
        lines.extend(
            (
                "\treturn eventSequence(func() (*eventStream, error) {",
                f"\t\treturn c.open{self.method_name}({arguments})",
                "\t})",
                "}",
            )
        )
        return "\n".join(lines)

    def render(self) -> list[str]:
        blocks: list[str] = []
        options = self.render_options()
        if options is not None:
            blocks.append(options)
        blocks.extend((self.render_builder(), self.render_method()))
        if self.operation.response.mode is ResponseMode.BYTES:
            blocks.append(self.render_method(stream_bytes=True))
        if self.operation.response.mode is ResponseMode.BYTE_STREAM:
            blocks.append(self.render_method(raw_stream=True))
        return blocks


def _render_imports(source: str) -> str:
    imports = {"context"}
    qualifiers = {
        "json.": "encoding/json",
        "fmt.": "fmt",
        "io.": "io",
        "iter.": "iter",
        "http.": "net/http",
        "url.": "net/url",
        "time.": "time",
    }
    imports.update(
        path for qualifier, path in qualifiers.items() if qualifier in source
    )
    lines = ["import ("]
    lines.extend(f"\t{_go_string(path)}" for path in sorted(imports))
    lines.append(")")
    return "\n".join(lines)


def render_operations(
    ir: SpecIR,
    package_name: str = DEFAULT_PACKAGE_NAME,
    *,
    extra_source: str = "",
) -> str:
    """Render request builders and public methods for all IR operations."""
    package_name = validate_package_name(package_name)
    renderers = {
        operation.name: _OperationRenderer(
            operation,
            {model.name: model for model in ir.models},
        )
        for operation in ir.operations
    }
    if len(renderers) != len(ir.operations):
        raise ValueError("IR has duplicate operation names")
    blocks = [block for renderer in renderers.values() for block in renderer.render()]
    if extra_source:
        blocks.append(extra_source)
    source = "\n\n".join(blocks)
    parts = [HEADER, f"package {package_name}"]
    if source:
        parts.extend((_render_imports(source), source))
    return "\n\n".join(parts) + "\n"
