// Code generated by codegen from the OpenAPI spec. DO NOT EDIT.

package contree

import (
	"context"
	"fmt"
	"io"
	"iter"
	"net/http"
	"net/url"
)

// ListImagesOptions contains optional arguments for ListImages.
type ListImagesOptions struct {
	Limit  *int64
	Offset *int64
	Tagged bool
	Tag    *string
	UUID   *string
	Since  *any
	Until  *any
}

func buildListImages(
	options *ListImagesOptions,
) (requestSpec, error) {
	query := make(url.Values)
	if options != nil && options.Limit != nil {
		if err := addQueryValue(query, "limit", *options.Limit, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Offset != nil {
		if err := addQueryValue(query, "offset", *options.Offset, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Tagged {
		if err := addQueryValue(query, "tagged", "1", false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Tag != nil {
		if err := addQueryValue(query, "tag", *options.Tag, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.UUID != nil {
		if err := addQueryValue(query, "uuid", *options.UUID, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Since != nil {
		formatted, err := formatTimeParam(*options.Since)
		if err != nil {
			return requestSpec{}, err
		}
		if err := addQueryValue(query, "since", formatted, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Until != nil {
		formatted, err := formatTimeParam(*options.Until)
		if err != nil {
			return requestSpec{}, err
		}
		if err := addQueryValue(query, "until", formatted, false); err != nil {
			return requestSpec{}, err
		}
	}
	requestPath := "/images"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// ListImages calls GET /images.
func (c *Client) ListImages(
	ctx context.Context,
	options *ListImagesOptions,
) (ImageListResponse, error) {
	spec, err := buildListImages(options)
	if err != nil {
		var zero ImageListResponse
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero ImageListResponse
		return zero, err
	}
	return decodeJSONResponse[ImageListResponse](response, acceptAny2xx)
}

// DeleteImageTagOptions contains optional arguments for DeleteImageTag.
type DeleteImageTagOptions struct {
	Tag *string
}

func buildDeleteImageTag(
	imageUUID string,
	options *DeleteImageTagOptions,
) (requestSpec, error) {
	query := make(url.Values)
	if options != nil && options.Tag != nil {
		if err := addQueryValue(query, "tag", *options.Tag, false); err != nil {
			return requestSpec{}, err
		}
	}
	requestPath := "/images/" + quotePath(imageUUID) + "/tag"
	return requestSpec{
		method:     "DELETE",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// DeleteImageTag calls DELETE /images/{imageUUID}/tag.
func (c *Client) DeleteImageTag(
	ctx context.Context,
	imageUUID string,
	options *DeleteImageTagOptions,
) error {
	spec, err := buildDeleteImageTag(imageUUID, options)
	if err != nil {
		return err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		return err
	}
	return emptyResponse(response, acceptAny2xx)
}

func buildUpdateImageTag(
	imageUUID string,
	tag string,
) (requestSpec, error) {
	payload := map[string]any{
		"tag": tag,
	}
	body, err := jsonBody(payload)
	if err != nil {
		return requestSpec{}, err
	}
	requestPath := "/images/" + quotePath(imageUUID) + "/tag"
	return requestSpec{
		method:      "PATCH",
		path:        requestPath,
		body:        body,
		contentType: "application/json",
		idempotent:  false,
	}, nil
}

// UpdateImageTag calls PATCH /images/{imageUUID}/tag.
func (c *Client) UpdateImageTag(
	ctx context.Context,
	imageUUID string,
	tag string,
) (Image, error) {
	spec, err := buildUpdateImageTag(imageUUID, tag)
	if err != nil {
		var zero Image
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero Image
		return zero, err
	}
	return decodeJSONResponse[Image](response, acceptAny2xx)
}

// ImportImageOptions contains optional arguments for ImportImage.
type ImportImageOptions struct {
	Tag     Optional[string]
	Timeout Optional[int64]
}

func buildImportImage(
	registry ImageImportRegistry,
	options *ImportImageOptions,
) (requestSpec, error) {
	payload := ImageImportRequest{
		Registry: registry,
	}
	if options != nil {
		payload.Tag = options.Tag
		payload.Timeout = options.Timeout
	}
	body, err := jsonBody(payload)
	if err != nil {
		return requestSpec{}, err
	}
	requestPath := "/images/import"
	return requestSpec{
		method:      "POST",
		path:        requestPath,
		body:        body,
		contentType: "application/json",
		idempotent:  false,
	}, nil
}

// ImportImage calls POST /images/import.
func (c *Client) ImportImage(
	ctx context.Context,
	registry ImageImportRegistry,
	options *ImportImageOptions,
) (string, error) {
	spec, err := buildImportImage(registry, options)
	if err != nil {
		var zero string
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero string
		return zero, err
	}
	return decodeJSONPathResponse[string](response, acceptAny2xx, "uuid")
}

// ListFilesOptions contains optional arguments for ListFiles.
type ListFilesOptions struct {
	Limit  *int64
	Offset *int64
	Since  *any
	Until  *any
}

func buildListFiles(
	options *ListFilesOptions,
) (requestSpec, error) {
	query := make(url.Values)
	if options != nil && options.Limit != nil {
		if err := addQueryValue(query, "limit", *options.Limit, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Offset != nil {
		if err := addQueryValue(query, "offset", *options.Offset, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Since != nil {
		formatted, err := formatTimeParam(*options.Since)
		if err != nil {
			return requestSpec{}, err
		}
		if err := addQueryValue(query, "since", formatted, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Until != nil {
		formatted, err := formatTimeParam(*options.Until)
		if err != nil {
			return requestSpec{}, err
		}
		if err := addQueryValue(query, "until", formatted, false); err != nil {
			return requestSpec{}, err
		}
	}
	requestPath := "/files"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// ListFiles calls GET /files.
func (c *Client) ListFiles(
	ctx context.Context,
	options *ListFilesOptions,
) (FilesListResponse, error) {
	spec, err := buildListFiles(options)
	if err != nil {
		var zero FilesListResponse
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero FilesListResponse
		return zero, err
	}
	return decodeJSONResponse[FilesListResponse](response, acceptAny2xx)
}

func buildUploadFile(
	content io.Reader,
) (requestSpec, error) {
	body := oneShotBody(content)
	requestPath := "/files"
	return requestSpec{
		method:      "POST",
		path:        requestPath,
		body:        body,
		contentType: "application/octet-stream",
		idempotent:  false,
	}, nil
}

// UploadFile calls POST /files.
func (c *Client) UploadFile(
	ctx context.Context,
	content io.Reader,
) (FileResponse, error) {
	spec, err := buildUploadFile(content)
	if err != nil {
		var zero FileResponse
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero FileResponse
		return zero, err
	}
	return decodeJSONResponse[FileResponse](response, acceptAny2xx)
}

func buildGetFile(
	sha256 string,
) (requestSpec, error) {
	requestPath := "/files/" + quotePath(sha256)
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		idempotent: true,
	}, nil
}

// GetFile calls GET /files/{sha256}.
func (c *Client) GetFile(
	ctx context.Context,
	sha256 string,
) (File, error) {
	spec, err := buildGetFile(sha256)
	if err != nil {
		var zero File
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero File
		return zero, err
	}
	return decodeJSONResponse[File](response, acceptAny2xx)
}

func buildCheckFileExists(
	sha256 string,
) (requestSpec, error) {
	requestPath := "/files/" + quotePath(sha256)
	return requestSpec{
		method:     "HEAD",
		path:       requestPath,
		idempotent: true,
	}, nil
}

// CheckFileExists calls HEAD /files/{sha256}.
func (c *Client) CheckFileExists(
	ctx context.Context,
	sha256 string,
) (bool, error) {
	spec, err := buildCheckFileExists(sha256)
	if err != nil {
		var zero bool
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero bool
		return zero, err
	}
	return booleanResponse(response, acceptAny2xx, 404)
}

// SpawnInstanceWithResponseOptions contains optional arguments for SpawnInstanceWithResponse.
type SpawnInstanceWithResponseOptions struct {
	Disposable       Optional[bool]
	Hostname         Optional[string]
	Args             Optional[[]string]
	Shell            Optional[bool]
	Env              Optional[map[string]string]
	PreserveEnv      Optional[bool]
	Cwd              Optional[string]
	UID              Optional[int64]
	GID              Optional[int64]
	ResourcesLimits  Optional[InstanceResourcesLimits]
	Networking       Optional[InstanceNetworking]
	Stdin            Optional[ClosableStreamRepr]
	Timeout          Optional[int64]
	TruncateOutputAt Optional[int64]
	Files            Optional[map[string]FileSpec]
}

func buildSpawnInstanceWithResponse(
	command string,
	image string,
	options *SpawnInstanceWithResponseOptions,
) (requestSpec, error) {
	payload := InstanceSpawnRequest{
		Command: command,
		Image:   image,
	}
	if options != nil {
		payload.Disposable = options.Disposable
		payload.Hostname = options.Hostname
		payload.Args = options.Args
		payload.Shell = options.Shell
		payload.Env = options.Env
		payload.PreserveEnv = options.PreserveEnv
		payload.Cwd = options.Cwd
		payload.UID = options.UID
		payload.GID = options.GID
		payload.ResourcesLimits = options.ResourcesLimits
		payload.Networking = options.Networking
		payload.Stdin = options.Stdin
		payload.Timeout = options.Timeout
		payload.TruncateOutputAt = options.TruncateOutputAt
		payload.Files = options.Files
	}
	body, err := jsonBody(payload)
	if err != nil {
		return requestSpec{}, err
	}
	requestPath := "/instances"
	return requestSpec{
		method:      "POST",
		path:        requestPath,
		body:        body,
		contentType: "application/json",
		idempotent:  false,
	}, nil
}

// SpawnInstanceWithResponse calls POST /instances.
func (c *Client) SpawnInstanceWithResponse(
	ctx context.Context,
	command string,
	image string,
	options *SpawnInstanceWithResponseOptions,
) (InstanceSpawnResponse, error) {
	spec, err := buildSpawnInstanceWithResponse(command, image, options)
	if err != nil {
		var zero InstanceSpawnResponse
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero InstanceSpawnResponse
		return zero, err
	}
	return decodeJSONResponse[InstanceSpawnResponse](response, acceptAny2xx)
}

// ListOperationsOptions contains optional arguments for ListOperations.
type ListOperationsOptions struct {
	Limit  *int64
	Offset *int64
	Status *OperationStatus
	Kind   *string
	Since  *any
	Until  *any
}

func buildListOperations(
	options *ListOperationsOptions,
) (requestSpec, error) {
	query := make(url.Values)
	if options != nil && options.Limit != nil {
		if err := addQueryValue(query, "limit", *options.Limit, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Offset != nil {
		if err := addQueryValue(query, "offset", *options.Offset, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Status != nil {
		if err := addQueryValue(query, "status", *options.Status, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Kind != nil {
		if err := addQueryValue(query, "kind", *options.Kind, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Since != nil {
		formatted, err := formatTimeParam(*options.Since)
		if err != nil {
			return requestSpec{}, err
		}
		if err := addQueryValue(query, "since", formatted, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Until != nil {
		formatted, err := formatTimeParam(*options.Until)
		if err != nil {
			return requestSpec{}, err
		}
		if err := addQueryValue(query, "until", formatted, false); err != nil {
			return requestSpec{}, err
		}
	}
	requestPath := "/operations"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// ListOperations calls GET /operations.
func (c *Client) ListOperations(
	ctx context.Context,
	options *ListOperationsOptions,
) ([]OperationSummary, error) {
	spec, err := buildListOperations(options)
	if err != nil {
		var zero []OperationSummary
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero []OperationSummary
		return zero, err
	}
	return decodeJSONResponse[[]OperationSummary](response, acceptAny2xx)
}

// GetOperationStatusOptions contains optional arguments for GetOperationStatus.
type GetOperationStatusOptions struct {
	Inflight bool
}

func buildGetOperationStatus(
	operationID string,
	options *GetOperationStatusOptions,
) (requestSpec, error) {
	query := make(url.Values)
	if options != nil && options.Inflight {
		if err := addQueryValue(query, "inflight", "1", false); err != nil {
			return requestSpec{}, err
		}
	}
	requestPath := "/operations/" + quotePath(operationID)
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// GetOperationStatus calls GET /operations/{operationId}.
func (c *Client) GetOperationStatus(
	ctx context.Context,
	operationID string,
	options *GetOperationStatusOptions,
) (OperationResponse, error) {
	spec, err := buildGetOperationStatus(operationID, options)
	if err != nil {
		var zero OperationResponse
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero OperationResponse
		return zero, err
	}
	return decodeJSONResponse[OperationResponse](response, acceptAny2xx)
}

func buildCancelOperation(
	operationID string,
) (requestSpec, error) {
	requestPath := "/operations/" + quotePath(operationID)
	return requestSpec{
		method:     "DELETE",
		path:       requestPath,
		idempotent: true,
	}, nil
}

// CancelOperation calls DELETE /operations/{operationId}.
func (c *Client) CancelOperation(
	ctx context.Context,
	operationID string,
) error {
	spec, err := buildCancelOperation(operationID)
	if err != nil {
		return err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		return err
	}
	return emptyResponse(response, acceptAny2xx)
}

// IterOperationEventsOptions contains optional arguments for IterOperationEvents.
type IterOperationEventsOptions struct {
	Follow      bool
	Spid        *int64
	Since       *int64
	LastEventID *int64
}

func buildIterOperationEvents(
	operationID string,
	options *IterOperationEventsOptions,
) (requestSpec, error) {
	query := make(url.Values)
	headers := make(http.Header)
	if options != nil && options.Follow {
		if err := addQueryValue(query, "follow", "1", false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Spid != nil {
		if err := addQueryValue(query, "spid", *options.Spid, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Since != nil {
		if err := addQueryValue(query, "since", *options.Since, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.LastEventID != nil {
		headers.Set("Last-Event-Id", fmt.Sprint(*options.LastEventID))
	}
	requestPath := "/operations/" + quotePath(operationID) + "/events"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		headers:    headers,
		accept:     "text/event-stream",
		idempotent: true,
	}, nil
}

// IterOperationEvents lazily yields operation events.
// Each traversal opens a new stream and closes it when iteration ends.
// The first error is yielded with a zero event, then iteration stops.
func (c *Client) IterOperationEvents(
	ctx context.Context,
	operationID string,
	options *IterOperationEventsOptions,
) iter.Seq2[OperationEvent, error] {
	return eventSequence(func() (*eventStream, error) {
		return c.openIterOperationEvents(ctx, operationID, options)
	})
}

// openIterOperationEvents calls GET /operations/{operationId}/events.
func (c *Client) openIterOperationEvents(
	ctx context.Context,
	operationID string,
	options *IterOperationEventsOptions,
) (*eventStream, error) {
	spec, err := buildIterOperationEvents(operationID, options)
	if err != nil {
		var zero *eventStream
		return zero, err
	}
	response, err := c.doStream(ctx, spec)
	if err != nil {
		var zero *eventStream
		return zero, err
	}
	return newEventStream(response, acceptAny2xx)
}

// OperationSubprocessCreateOptions contains optional arguments for OperationSubprocessCreate.
type OperationSubprocessCreateOptions struct {
	Args             Optional[[]string]
	Shell            Optional[bool]
	Env              Optional[map[string]string]
	Cwd              Optional[string]
	UID              Optional[int64]
	GID              Optional[int64]
	Stdin            Optional[ClosableStreamRepr]
	TruncateOutputAt Optional[int64]
}

func buildOperationSubprocessCreate(
	operationID string,
	command string,
	options *OperationSubprocessCreateOptions,
) (requestSpec, error) {
	payload := ExecSpec{
		Command: command,
	}
	if options != nil {
		payload.Args = options.Args
		payload.Shell = options.Shell
		payload.Env = options.Env
		payload.Cwd = options.Cwd
		payload.UID = options.UID
		payload.GID = options.GID
		payload.Stdin = options.Stdin
		payload.TruncateOutputAt = options.TruncateOutputAt
	}
	body, err := jsonBody(payload)
	if err != nil {
		return requestSpec{}, err
	}
	requestPath := "/operations/" + quotePath(operationID) + "/subprocesses"
	return requestSpec{
		method:      "POST",
		path:        requestPath,
		body:        body,
		contentType: "application/json",
		idempotent:  false,
	}, nil
}

// OperationSubprocessCreate calls POST /operations/{operationId}/subprocesses.
func (c *Client) OperationSubprocessCreate(
	ctx context.Context,
	operationID string,
	command string,
	options *OperationSubprocessCreateOptions,
) (int64, error) {
	spec, err := buildOperationSubprocessCreate(operationID, command, options)
	if err != nil {
		var zero int64
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero int64
		return zero, err
	}
	return decodeJSONPathResponse[int64](response, acceptAny2xx, "spid")
}

func buildOperationSubprocess(
	operationID string,
	spid int64,
) (requestSpec, error) {
	requestPath := "/operations/" + quotePath(operationID) + "/subprocesses/" + quotePath(spid)
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		idempotent: true,
	}, nil
}

// OperationSubprocess calls GET /operations/{operationId}/subprocesses/{spid}.
func (c *Client) OperationSubprocess(
	ctx context.Context,
	operationID string,
	spid int64,
) (InstanceResult, error) {
	spec, err := buildOperationSubprocess(operationID, spid)
	if err != nil {
		var zero InstanceResult
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero InstanceResult
		return zero, err
	}
	return decodeJSONResponse[InstanceResult](response, acceptAny2xx)
}

// OperationSubprocessKillOptions contains optional arguments for OperationSubprocessKill.
type OperationSubprocessKillOptions struct {
	Signal *string
}

func buildOperationSubprocessKill(
	operationID string,
	spid int64,
	options *OperationSubprocessKillOptions,
) (requestSpec, error) {
	query := make(url.Values)
	if options != nil && options.Signal != nil {
		if err := addQueryValue(query, "signal", *options.Signal, false); err != nil {
			return requestSpec{}, err
		}
	}
	requestPath := "/operations/" + quotePath(operationID) + "/subprocesses/" + quotePath(spid)
	return requestSpec{
		method:     "DELETE",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// OperationSubprocessKill calls DELETE /operations/{operationId}/subprocesses/{spid}.
func (c *Client) OperationSubprocessKill(
	ctx context.Context,
	operationID string,
	spid int64,
	options *OperationSubprocessKillOptions,
) error {
	spec, err := buildOperationSubprocessKill(operationID, spid, options)
	if err != nil {
		return err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		return err
	}
	return emptyResponse(response, acceptAny2xx)
}

// OperationSubprocessStdinOptions contains optional arguments for OperationSubprocessStdin.
type OperationSubprocessStdinOptions struct {
	Encoding Optional[string]
	Close    Optional[bool]
}

func buildOperationSubprocessStdin(
	operationID string,
	spid int64,
	valueArg string,
	options *OperationSubprocessStdinOptions,
) (requestSpec, error) {
	payload := ClosableStreamRepr{
		Value: valueArg,
	}
	if options != nil {
		payload.Encoding = options.Encoding
		payload.Close = options.Close
	}
	body, err := jsonBody(payload)
	if err != nil {
		return requestSpec{}, err
	}
	requestPath := "/operations/" + quotePath(operationID) + "/subprocesses/" + quotePath(spid) + "/stdin"
	return requestSpec{
		method:      "POST",
		path:        requestPath,
		body:        body,
		contentType: "application/json",
		idempotent:  false,
	}, nil
}

// OperationSubprocessStdin calls POST /operations/{operationId}/subprocesses/{spid}/stdin.
func (c *Client) OperationSubprocessStdin(
	ctx context.Context,
	operationID string,
	spid int64,
	valueArg string,
	options *OperationSubprocessStdinOptions,
) error {
	spec, err := buildOperationSubprocessStdin(operationID, spid, valueArg, options)
	if err != nil {
		return err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		return err
	}
	return emptyResponse(response, acceptAny2xx)
}

func buildInspectFindImageByTag(
	tag string,
) (requestSpec, error) {
	query := make(url.Values)
	if err := addQueryValue(query, "tag", tag, false); err != nil {
		return requestSpec{}, err
	}
	requestPath := "/inspect/"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// InspectFindImageByTag calls GET /inspect/.
func (c *Client) InspectFindImageByTag(
	ctx context.Context,
	tag string,
) (string, error) {
	spec, err := buildInspectFindImageByTag(tag)
	if err != nil {
		var zero string
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero string
		return zero, err
	}
	return locationResponse(response, acceptStatuses(302), "location")
}

func buildInspectImage(
	imageUUID string,
) (requestSpec, error) {
	requestPath := "/inspect/" + quotePath(imageUUID) + "/"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		idempotent: true,
	}, nil
}

// InspectImage calls GET /inspect/{image_uuid}/.
func (c *Client) InspectImage(
	ctx context.Context,
	imageUUID string,
) (Image, error) {
	spec, err := buildInspectImage(imageUUID)
	if err != nil {
		var zero Image
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero Image
		return zero, err
	}
	return decodeJSONResponse[Image](response, acceptAny2xx)
}

func buildInspectImageDownload(
	imageUUID string,
	path string,
) (requestSpec, error) {
	query := make(url.Values)
	if err := addQueryValue(query, "path", path, false); err != nil {
		return requestSpec{}, err
	}
	requestPath := "/inspect/" + quotePath(imageUUID) + "/download"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// InspectImageDownload calls GET /inspect/{image_uuid}/download.
func (c *Client) InspectImageDownload(
	ctx context.Context,
	imageUUID string,
	path string,
) ([]byte, error) {
	spec, err := buildInspectImageDownload(imageUUID, path)
	if err != nil {
		var zero []byte
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero []byte
		return zero, err
	}
	return byteResponse(response, acceptAny2xx)
}

// InspectImageDownloadStream streams the response body from InspectImageDownload.
func (c *Client) InspectImageDownloadStream(
	ctx context.Context,
	imageUUID string,
	path string,
) (io.ReadCloser, error) {
	spec, err := buildInspectImageDownload(imageUUID, path)
	if err != nil {
		var zero io.ReadCloser
		return zero, err
	}
	response, err := c.doStream(ctx, spec)
	if err != nil {
		var zero io.ReadCloser
		return zero, err
	}
	return streamResponse(response, acceptAny2xx)
}

func buildCheckImageFile(
	imageUUID string,
	path string,
) (requestSpec, error) {
	query := make(url.Values)
	if err := addQueryValue(query, "path", path, false); err != nil {
		return requestSpec{}, err
	}
	requestPath := "/inspect/" + quotePath(imageUUID) + "/download"
	return requestSpec{
		method:     "HEAD",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// CheckImageFile calls HEAD /inspect/{image_uuid}/download.
func (c *Client) CheckImageFile(
	ctx context.Context,
	imageUUID string,
	path string,
) (bool, error) {
	spec, err := buildCheckImageFile(imageUUID, path)
	if err != nil {
		var zero bool
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero bool
		return zero, err
	}
	return booleanResponse(response, acceptAny2xx, 404)
}

func buildInspectImageArchive(
	imageUUID string,
	path string,
) (requestSpec, error) {
	query := make(url.Values)
	if err := addQueryValue(query, "path", path, false); err != nil {
		return requestSpec{}, err
	}
	requestPath := "/inspect/" + quotePath(imageUUID) + "/archive"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// InspectImageArchive calls GET /inspect/{image_uuid}/archive.
func (c *Client) InspectImageArchive(
	ctx context.Context,
	imageUUID string,
	path string,
) (io.ReadCloser, error) {
	spec, err := buildInspectImageArchive(imageUUID, path)
	if err != nil {
		var zero io.ReadCloser
		return zero, err
	}
	response, err := c.doStream(ctx, spec)
	if err != nil {
		var zero io.ReadCloser
		return zero, err
	}
	return streamResponse(response, acceptAny2xx)
}

// InspectImageArchiveRaw streams the encoded response body from InspectImageArchive.
func (c *Client) InspectImageArchiveRaw(
	ctx context.Context,
	imageUUID string,
	path string,
) (io.ReadCloser, error) {
	spec, err := buildInspectImageArchive(imageUUID, path)
	if err != nil {
		var zero io.ReadCloser
		return zero, err
	}
	response, err := c.doRawStream(ctx, spec)
	if err != nil {
		var zero io.ReadCloser
		return zero, err
	}
	return rawStreamResponse(response, acceptAny2xx)
}

func buildCheckImageArchive(
	imageUUID string,
	path string,
) (requestSpec, error) {
	query := make(url.Values)
	if err := addQueryValue(query, "path", path, false); err != nil {
		return requestSpec{}, err
	}
	requestPath := "/inspect/" + quotePath(imageUUID) + "/archive"
	return requestSpec{
		method:     "HEAD",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// CheckImageArchive calls HEAD /inspect/{image_uuid}/archive.
func (c *Client) CheckImageArchive(
	ctx context.Context,
	imageUUID string,
	path string,
) (bool, error) {
	spec, err := buildCheckImageArchive(imageUUID, path)
	if err != nil {
		var zero bool
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero bool
		return zero, err
	}
	return booleanResponse(response, acceptAny2xx, 404)
}

func buildInspectImageList(
	imageUUID string,
	path string,
) (requestSpec, error) {
	query := make(url.Values)
	if err := addQueryValue(query, "path", path, false); err != nil {
		return requestSpec{}, err
	}
	requestPath := "/inspect/" + quotePath(imageUUID) + "/list"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// InspectImageList calls GET /inspect/{image_uuid}/list.
func (c *Client) InspectImageList(
	ctx context.Context,
	imageUUID string,
	path string,
) (DirectoryList, error) {
	spec, err := buildInspectImageList(imageUUID, path)
	if err != nil {
		var zero DirectoryList
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero DirectoryList
		return zero, err
	}
	return decodeJSONResponse[DirectoryList](response, acceptAny2xx)
}

// InspectImageGrepOptions contains optional arguments for InspectImageGrep.
type InspectImageGrepOptions struct {
	Path     *[]string
	Glob     *[]string
	MaxCount *int64
	MaxTotal *int64
	Case     *string
	Before   *int64
	After    *int64
}

func buildInspectImageGrep(
	imageUUID string,
	pattern []string,
	options *InspectImageGrepOptions,
) (requestSpec, error) {
	query := make(url.Values)
	if err := addQueryValue(query, "pattern", pattern, true); err != nil {
		return requestSpec{}, err
	}
	if options != nil && options.Path != nil {
		if err := addQueryValue(query, "path", *options.Path, true); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Glob != nil {
		if err := addQueryValue(query, "glob", *options.Glob, true); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.MaxCount != nil {
		if err := addQueryValue(query, "max_count", *options.MaxCount, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.MaxTotal != nil {
		if err := addQueryValue(query, "max_total", *options.MaxTotal, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Case != nil {
		if err := addQueryValue(query, "case", *options.Case, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.Before != nil {
		if err := addQueryValue(query, "before", *options.Before, false); err != nil {
			return requestSpec{}, err
		}
	}
	if options != nil && options.After != nil {
		if err := addQueryValue(query, "after", *options.After, false); err != nil {
			return requestSpec{}, err
		}
	}
	requestPath := "/inspect/" + quotePath(imageUUID) + "/grep"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		query:      query,
		idempotent: true,
	}, nil
}

// InspectImageGrep calls GET /inspect/{image_uuid}/grep.
func (c *Client) InspectImageGrep(
	ctx context.Context,
	imageUUID string,
	pattern []string,
	options *InspectImageGrepOptions,
) (GrepResult, error) {
	spec, err := buildInspectImageGrep(imageUUID, pattern, options)
	if err != nil {
		var zero GrepResult
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero GrepResult
		return zero, err
	}
	return decodeJSONResponse[GrepResult](response, acceptAny2xx)
}

func buildWhoAmI() (requestSpec, error) {
	requestPath := "/whoami"
	return requestSpec{
		method:     "GET",
		path:       requestPath,
		idempotent: true,
	}, nil
}

// WhoAmI calls GET /whoami.
func (c *Client) WhoAmI(
	ctx context.Context,
) (WhoAmIResponse, error) {
	spec, err := buildWhoAmI()
	if err != nil {
		var zero WhoAmIResponse
		return zero, err
	}
	response, err := c.do(ctx, spec)
	if err != nil {
		var zero WhoAmIResponse
		return zero, err
	}
	return decodeJSONResponse[WhoAmIResponse](response, acceptAny2xx)
}

// IterImagesOptions configures IterImages.
type IterImagesOptions struct {
	// PageSize is the number of items requested per page. Zero uses 1000.
	PageSize int64
	// Limit bounds the total item count. Nil requests all items.
	Limit  *int64
	Tagged bool
	Tag    *string
	UUID   *string
	Since  *any
	Until  *any
}

// IterImages lazily iterates ListImages pages.
// Each traversal starts from the first page. The first error is yielded
// with a zero item, then iteration stops. Break stops fetching pages.
func (c *Client) IterImages(
	ctx context.Context,
	options *IterImagesOptions,
) iter.Seq2[Image, error] {
	var pageSize int64
	var limit *int64
	if options != nil {
		pageSize = options.PageSize
		limit = options.Limit
	}
	filters := ListImagesOptions{}
	if options != nil {
		filters.Tagged = options.Tagged
		filters.Tag = options.Tag
		filters.UUID = options.UUID
		filters.Since = options.Since
		filters.Until = options.Until
	}
	return iteratePages[Image](
		ctx,
		pageSize,
		1000,
		limit,
		func(pageSize, offset int64) ([]Image, error) {
			requestOptions := filters
			requestOptions.Limit = &pageSize
			requestOptions.Offset = &offset
			response, err := c.ListImages(ctx, &requestOptions)
			if err != nil {
				return nil, err
			}
			pageValue1, ok := response.Images.Value()
			if !ok {
				return nil, nil
			}
			return pageValue1, nil
		},
	)
}

// IterFilesOptions configures IterFiles.
type IterFilesOptions struct {
	// PageSize is the number of items requested per page. Zero uses 1000.
	PageSize int64
	// Limit bounds the total item count. Nil requests all items.
	Limit *int64
	Since *any
	Until *any
}

// IterFiles lazily iterates ListFiles pages.
// Each traversal starts from the first page. The first error is yielded
// with a zero item, then iteration stops. Break stops fetching pages.
func (c *Client) IterFiles(
	ctx context.Context,
	options *IterFilesOptions,
) iter.Seq2[File, error] {
	var pageSize int64
	var limit *int64
	if options != nil {
		pageSize = options.PageSize
		limit = options.Limit
	}
	filters := ListFilesOptions{}
	if options != nil {
		filters.Since = options.Since
		filters.Until = options.Until
	}
	return iteratePages[File](
		ctx,
		pageSize,
		1000,
		limit,
		func(pageSize, offset int64) ([]File, error) {
			requestOptions := filters
			requestOptions.Limit = &pageSize
			requestOptions.Offset = &offset
			response, err := c.ListFiles(ctx, &requestOptions)
			if err != nil {
				return nil, err
			}
			pageValue1, ok := response.Files.Value()
			if !ok {
				return nil, nil
			}
			return pageValue1, nil
		},
	)
}

// IterOperationsOptions configures IterOperations.
type IterOperationsOptions struct {
	// PageSize is the number of items requested per page. Zero uses 1000.
	PageSize int64
	// Limit bounds the total item count. Nil requests all items.
	Limit  *int64
	Status *OperationStatus
	Kind   *string
	Since  *any
	Until  *any
}

// IterOperations lazily iterates ListOperations pages.
// Each traversal starts from the first page. The first error is yielded
// with a zero item, then iteration stops. Break stops fetching pages.
func (c *Client) IterOperations(
	ctx context.Context,
	options *IterOperationsOptions,
) iter.Seq2[OperationSummary, error] {
	var pageSize int64
	var limit *int64
	if options != nil {
		pageSize = options.PageSize
		limit = options.Limit
	}
	filters := ListOperationsOptions{}
	if options != nil {
		filters.Status = options.Status
		filters.Kind = options.Kind
		filters.Since = options.Since
		filters.Until = options.Until
	}
	return iteratePages[OperationSummary](
		ctx,
		pageSize,
		1000,
		limit,
		func(pageSize, offset int64) ([]OperationSummary, error) {
			requestOptions := filters
			requestOptions.Limit = &pageSize
			requestOptions.Offset = &offset
			response, err := c.ListOperations(ctx, &requestOptions)
			if err != nil {
				return nil, err
			}
			return response, nil
		},
	)
}
