// Code generated by codegen from the OpenAPI spec. DO NOT EDIT.

package contree

const DefaultBaseURL = "https://api.tokenfactory.nebius.com/sandboxes"

// SpecSHA256 identifies the exact OpenAPI input document.
const SpecSHA256 = "23d748a2918b1124b3072d54d17d8eb43aa00d0b969bc1fa718f34ac884ee887"
