// Code generated by codegen from the OpenAPI spec. DO NOT EDIT.
package contree

type mockOperation struct {
	name        string
	method      string
	path        string
	mode        string
	status      int
	falseStatus int
	header      string
	jsonPath    []string
	aliases     []string
}

var mockOperations = []mockOperation{
	{
		name:   "ListImages",
		method: "GET",
		path:   "/images",
		mode:   "JSON",
		status: 200,
	},
	{
		name:   "DeleteImageTag",
		method: "DELETE",
		path:   "/images/{imageUUID}/tag",
		mode:   "EMPTY",
		status: 204,
	},
	{
		name:   "UpdateImageTag",
		method: "PATCH",
		path:   "/images/{imageUUID}/tag",
		mode:   "JSON",
		status: 200,
	},
	{
		name:     "ImportImage",
		method:   "POST",
		path:     "/images/import",
		mode:     "JSON",
		status:   201,
		jsonPath: []string{"uuid"},
	},
	{
		name:   "ListFiles",
		method: "GET",
		path:   "/files",
		mode:   "JSON",
		status: 200,
	},
	{
		name:   "UploadFile",
		method: "POST",
		path:   "/files",
		mode:   "JSON",
		status: 201,
	},
	{
		name:   "GetFile",
		method: "GET",
		path:   "/files/{sha256}",
		mode:   "JSON",
		status: 200,
	},
	{
		name:        "CheckFileExists",
		method:      "HEAD",
		path:        "/files/{sha256}",
		mode:        "STATUS_BOOL",
		status:      200,
		falseStatus: 404,
	},
	{
		name:    "SpawnInstance",
		method:  "POST",
		path:    "/instances",
		mode:    "JSON",
		status:  201,
		aliases: []string{"SpawnInstanceWithResponse"},
	},
	{
		name:   "ListOperations",
		method: "GET",
		path:   "/operations",
		mode:   "JSON",
		status: 200,
	},
	{
		name:   "GetOperationStatus",
		method: "GET",
		path:   "/operations/{operationId}",
		mode:   "JSON",
		status: 200,
	},
	{
		name:   "CancelOperation",
		method: "DELETE",
		path:   "/operations/{operationId}",
		mode:   "EMPTY",
		status: 202,
	},
	{
		name:   "IterOperationEvents",
		method: "GET",
		path:   "/operations/{operationId}/events",
		mode:   "SSE",
		status: 200,
	},
	{
		name:     "OperationSubprocessCreate",
		method:   "POST",
		path:     "/operations/{operationId}/subprocesses",
		mode:     "JSON",
		status:   201,
		jsonPath: []string{"spid"},
	},
	{
		name:   "OperationSubprocess",
		method: "GET",
		path:   "/operations/{operationId}/subprocesses/{spid}",
		mode:   "JSON",
		status: 200,
	},
	{
		name:   "OperationSubprocessKill",
		method: "DELETE",
		path:   "/operations/{operationId}/subprocesses/{spid}",
		mode:   "EMPTY",
		status: 204,
	},
	{
		name:   "OperationSubprocessStdin",
		method: "POST",
		path:   "/operations/{operationId}/subprocesses/{spid}/stdin",
		mode:   "EMPTY",
		status: 204,
	},
	{
		name:   "InspectFindImageByTag",
		method: "GET",
		path:   "/inspect/",
		mode:   "LOCATION",
		status: 302,
		header: "location",
	},
	{
		name:   "InspectImage",
		method: "GET",
		path:   "/inspect/{image_uuid}/",
		mode:   "JSON",
		status: 200,
	},
	{
		name:    "InspectImageDownload",
		method:  "GET",
		path:    "/inspect/{image_uuid}/download",
		mode:    "BYTES",
		status:  200,
		aliases: []string{"InspectImageDownloadStream"},
	},
	{
		name:        "CheckImageFile",
		method:      "HEAD",
		path:        "/inspect/{image_uuid}/download",
		mode:        "STATUS_BOOL",
		status:      200,
		falseStatus: 404,
	},
	{
		name:    "InspectImageArchive",
		method:  "GET",
		path:    "/inspect/{image_uuid}/archive",
		mode:    "BYTE_STREAM",
		status:  200,
		aliases: []string{"InspectImageArchiveRaw"},
	},
	{
		name:        "CheckImageArchive",
		method:      "HEAD",
		path:        "/inspect/{image_uuid}/archive",
		mode:        "STATUS_BOOL",
		status:      200,
		falseStatus: 404,
	},
	{
		name:   "InspectImageList",
		method: "GET",
		path:   "/inspect/{image_uuid}/list",
		mode:   "JSON",
		status: 200,
	},
	{
		name:   "InspectImageGrep",
		method: "GET",
		path:   "/inspect/{image_uuid}/grep",
		mode:   "JSON",
		status: 200,
	},
	{
		name:   "WhoAmI",
		method: "GET",
		path:   "/whoami",
		mode:   "JSON",
		status: 200,
	},
}
